server:
  port: "8080"
  readTimeout: "10s"
  writeTimeout: "30s"
  idleTimeout: "120s"

analyzer:
  timeout: "30s"
  maxConcurrentLinks: 10
  userAgent: "WebPageAnalyzer/1.0"
  retryAttempts: 3
  maxLinksPerPage: 100
  maxDepth: 2
  enableMetrics: true
  metricsPrefix: "webpage_analyzer" 